Ext.define('CMDBuildUI.store.attributes.AttributeTypes', {
    extend: 'Ext.data.Store',
    alias: 'store.attributes-attributetypes',
    
    requires: [
        'CMDBuildUI.model.base.ComboItem'
    ],

    model: 'CMDBuildUI.model.base.ComboItem',

    data: [{
        label: 'BOOLEAN',
        value: 'boolean',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'CHAR',
        value: 'char',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'DATE',
        value: 'date',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'DECIMAL',
        value: 'decimal',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'DOUBLE',
        value: 'double',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'INTEGER',
        value: 'integer',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'IP_ADDRESS',
        value: 'ipAddress',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'LOOKUP',
        value: 'lookup',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'REFERENCE',
        value: 'reference',
        _isForStandardClass: true,
        _isForSimpleClass: false,
        _isForDomain: false,
        _isForProcess: true
    }, {
        label: 'STRING',
        value: 'string',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'TEXT',
        value: 'text',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'TIME',
        value: 'time',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    }, {
        label: 'TIMESTAMP',
        value: 'dateTime',
        _isForStandardClass: true,
        _isForSimpleClass: true,
        _isForDomain: true,
        _isForProcess: true
    },{
        label: 'JSON',
        value: 'json',
        _isForStandardClass: false,
        _isForSimpleClass: false,
        _isForDomain: false,
        _isForProcess: true
    }, {
        label: 'FOREIGNKEY',
        value: 'foreignKey',
        _isForStandardClass: false,
        _isForSimpleClass: true,
        _isForDomain: false,
        _isForProcess: false
    }],
    proxy: {
        type: 'memory'
    }
});